---
title: Bartłomiej Misiuda | Strona Domowa Artysty
author: 'Bartłomiej Misiuda '
email: 'musicmaster '
description: Bartłomiej Misiuda, Baryton
baseurl: "/ubuild-jekyll"
url: ''
defaults: []
plugins:
- jekyll-feed
- jekyll-menus
